openapi: 3.0.0
info:
  contact: {}
  description: Bearer token認証
  title: Newsfeed & Why is it Moving v2
  version: 2.0.0
paths:
  /api/v2.1/news/channels:
    get:
      description: ニュース項目のフィルタリングに使用できる、利用可能なすべてのニュースチャンネルの一覧を返します。チャンネルにはサブチャンネルが含まれる場合もありますが、それぞれ個別の項目として一覧表示されます。
      operationId: get-channels
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
        "500":
          description: 内部サーバーエラー
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
      summary: 利用可能なニュースチャンネルを取得
      tags:
        - Channels
  /api/v2/news:
    get:
      description: このREST
        APIは、ニュースの構造化データを返します。最適なパフォーマンスを得るには、tickers、date、channelsなどのパラメータを使用してクエリの範囲を絞り込むか、差分取得にはupdatedSinceを使用してください。ページオフセットは0～100000に制限されています。
      operationId: get-news
      parameters:
        - description: 返却形式を指定
          in: header
          name: accept
          required: true
          schema:
            type: string
            enum:
              - application/json
              - application/xml
            default: application/json
        - description: ページオフセット。最適化、パフォーマンス、および技術的な理由により、ページオフセットは0～100000に制限されています。dateなどの他のパラメータでクエリ結果を絞り込んでください。
          in: query
          name: page
          schema:
            type: integer
            default: 0
        - description: 返される結果数。最大100。
          in: query
          name: pageSize
          schema:
            type: integer
            maximum: 100
            default: 15
        - description: 見出しのみ（headline）、見出し + 要約（abstract）、または見出し + 本文全文（full）を指定
          in: query
          name: displayOutput
          schema:
            type: string
            enum:
              - full
              - abstract
              - headline
            default: headline
        - description: "ニュースの照会対象の日付。dateFromとdateToが同じ場合の省略記法です。形式: yyyy-mm-dd"
          in: query
          name: date
          schema:
            type: string
        - description: "照会開始時点の日付。公開日でソートされます。形式: yyyy-mm-dd"
          in: query
          name: dateFrom
          schema:
            type: string
        - description: "照会終了時点の日付。公開日でソートされます。形式: yyyy-mm-dd"
          in: query
          name: dateTo
          schema:
            type: string
        - description: 取得およびソートの基準となる最終更新Unixタイムスタンプ（UTC）
          in: query
          name: updatedSince
          schema:
            type: integer
        - description: 取得およびソートの基準となる最終公開Unixタイムスタンプ（UTC）
          in: query
          name: publishedSince
          schema:
            type: integer
        - description: "結果の並び順を制御できます。デフォルトはcreated, DESCです。形式: field:direction。ソート項目:
            id、created、updated。ソート順: asc（昇順）、desc（降順）"
          in: query
          name: sort
          schema:
            type: string
            enum:
              - id:asc
              - id:desc
              - created:asc
              - created:desc
              - updated:asc
              - updated:desc
        - description: "カンマ区切りの1つ以上のISIN。最大50。形式: csv"
          in: query
          name: isin
          schema:
            type: string
        - description: "カンマ区切りの1つ以上のCUSIP。最大50。ライセンス契約が必要です。形式: csv"
          in: query
          name: cusips
          schema:
            type: string
        - description: "カンマ区切りの1つ以上のティッカーシンボル。最大50。形式: csv"
          in: query
          name: tickers
          schema:
            type: string
        - description: "カンマ区切りの1つ以上のプライマリティッカーシンボル。プライマリティッカーとの関連付けでのみ絞り込みます。形式: csv"
          in: query
          name: primaryTickers
          schema:
            type: string
        - description: "カンマ区切りの1つ以上のチャンネル名またはID。形式: csv"
          in: query
          name: channels
          schema:
            type: string
        - description: "カンマ区切りの1つ以上の単語またはフレーズ。優先順位に従ってTitle、Tags、Bodyを検索します。形式: csv"
          in: query
          name: topics
          schema:
            type: string
        - description: topicsクエリの論理演算子。すべてのtopicsを必須にするには'and'、いずれかのtopicを必須にするには'or'を使用します
          in: query
          name: topic_group_by
          schema:
            type: string
            enum:
              - and
              - or
            default: or
        - description: "カンマ区切りの1人以上の著者。形式: csv"
          in: query
          name: authors
          schema:
            type: string
        - description: "カンマ区切りの1つ以上のコンテンツタイプ。形式: csv"
          in: query
          name: content_types
          schema:
            type: string
        - description: APIレスポンスの返却形式を指定
          in: query
          name: format
          schema:
            type: string
            enum:
              - text
        - description: 重要度で絞り込み
          in: query
          name: importance
          schema:
            type: string
        - description: "地域で絞り込み（例: カナダ向けコンテンツの場合は'ca'または'canada'）"
          in: query
          name: region
          schema:
            type: string
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/api.NewsItem"
                type: array
            text/xml:
              schema:
                items:
                  $ref: "#/components/schemas/api.NewsItem"
                type: array
        "400":
          description: クエリパラメータが無効または不足しています
          content:
            application/json:
              schema:
                type: string
            text/xml:
              schema:
                type: string
        "499":
          description: リクエストコンテキストがキャンセルされました
          content:
            application/json:
              schema:
                type: string
            text/xml:
              schema:
                type: string
        "500":
          description: 内部エラー
          content:
            application/json:
              schema:
                type: string
            text/xml:
              schema:
                type: string
      security:
        - ApiKeyAuth: []
      summary: ニュース項目を取得
      tags:
        - News
  /api/v2/news-removed:
    get:
      description: 削除済みのニュースデータを返します。指定したタイムスタンプ以降に更新された項目のみが結果に含まれます。
      operationId: get-removed-news
      parameters:
        - description: 返却形式を指定します
          in: header
          name: accept
          required: true
          schema:
            type: string
            enum:
              - application/json
            default: application/json
        - description: ページオフセットです。最適化、パフォーマンス、および技術上の理由から、ページオフセットは 0～100000
            の範囲に制限されています。date などの他のパラメータでクエリ結果を絞り込んでください。
          in: query
          name: page
          schema:
            type: integer
            default: 0
        - description: 返される結果数です。最大 100 件です。
          in: query
          name: pageSize
          schema:
            type: integer
            maximum: 100
            default: 15
        - description: 指定した Unix タイムスタンプ（UTC）以降に更新された項目のみが結果に含まれます
          in: query
          name: updatedSince
          schema:
            type: integer
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                additionalProperties:
                  items:
                    $ref: "#/components/schemas/api.NewsRemovedItem"
                  type: array
                type: object
        "400":
          description: クエリパラメータが無効または不足しています
          content:
            application/json:
              schema:
                type: string
        "499":
          description: リクエストコンテキストがキャンセルされました
          content:
            application/json:
              schema:
                type: string
        "500":
          description: 内部エラー
          content:
            application/json:
              schema:
                type: string
      security:
        - ApiKeyAuth: []
      summary: 削除済みのニュースデータを返します
      tags:
        - News
servers:
  - url: //api.benzinga.com/api/v2
components:
  securitySchemes:
    ApiKeyAuth:
      description: APIキー認証です。APIキーをクエリパラメータとして指定してください。
      in: query
      name: token
      type: apiKey
  schemas:
    api.ChannelTag:
      description: チャンネル名またはタグ名
      properties:
        name:
          example: Technology
          type: string
      type: object
    api.Image:
      description: サイズと URL を含む記事画像
      properties:
        size:
          example: large
          type: string
        url:
          example: https://cdn.benzinga.com/files/images/story/2024/example.jpg
          type: string
      type: object
    api.NewsItem:
      description: 完全なメタデータを含むニュース記事項目
      properties:
        author:
          example: Benzinga Newsdesk
          type: string
        body:
          type: string
        channels:
          items:
            $ref: "#/components/schemas/api.ChannelTag"
          type: array
        created:
          example: Wed, 17 May 2017 14:20:15 -0400
          type: string
        id:
          example: 123456
          type: integer
        image:
          items:
            $ref: "#/components/schemas/api.Image"
          type: array
        original_id:
          type: integer
        stocks:
          items:
            $ref: "#/components/schemas/api.Stock"
          type: array
        tags:
          items:
            $ref: "#/components/schemas/api.ChannelTag"
          type: array
        teaser:
          type: string
        title:
          example: Apple Announces New iPhone
          type: string
        updated:
          example: Wed, 17 May 2017 14:20:15 -0400
          type: string
        url:
          example: https://www.benzinga.com/news/123456
          type: string
      type: object
    api.NewsRemovedItem:
      description: ID と更新タイムスタンプを含む削除済みニュース記事
      properties:
        id:
          example: 123456
          type: integer
        updated:
          example: Wed, 17 May 2017 14:20:15 -0400
          type: string
      type: object
    api.Stock:
      description: ティッカーシンボルと識別子を含む株式情報
      properties:
        cusip:
          example: "037833100"
          type: string
        exchange:
          example: NASDAQ
          type: string
        isin:
          example: US0378331005
          type: string
        name:
          example: AAPL
          type: string
      type: object
